### ISSUE TITLE
Todo list of new official website of Mark Text

### ISSUE THREAD

**Issue by Jocs** [marktext/website#8]
- [ ] Add Feature detail page.
- [ ] Add sponsor page.
- [ ] Click buttons in nav bar will scroll to relative page.
- [ ] Change title in theme page.
- [ ] Change all pictures in feature page to html, because pictures load slowly and can not change themes.
- [ ] Change log and User Guide.
- [ ] Auto update download link and CHANGE LOG after Mark Text release new version.(auto create a PR?)

Optimization:
- [ ] load css as string. now we used a `js` file not a `css` file.
- [ ] Change icon colors.

**Comment by Lisiadito** [comment]
Regarding the point of the release links I have an idea.
You can use following format: `https://github.com/marktext/marktext/releases/latest/download/marktext-setup.exe`
Then you would just need to change the naming convention and not add the version number into the filename.

**Comment by Jocs** [comment]
PRs also welcomed.

**Comment by Lisiadito** [comment]
Sure I can make a PR for the website links.
But it must not be merged before the next release because at the moment the naming is e.g. `marktext-setup-<version_number>.exe` and would need to be `marktext-setup.exe` in the future in order to work with the links.

**Comment by Jocs** [comment]
>But it must not be merged before the next release because at the moment the naming is e.g. marktext-setup-<version_number>.exe and would need to be marktext-setup.exe in the future in order to work with the links.

I understand what you mean now, it seems that we need the `version number`, Sorry for misunderstand what you say.

**Comment by fxha** [comment]
> > But it must not be merged before the next release because at the moment the naming is e.g. marktext-setup-<version_number>.exe and would need to be marktext-setup.exe in the future in order to work with the links.
> 
> I understand what you mean now, it seems that we need the `version number`, Sorry for misunderstand what you say.

I don't think so because the version was included by default and we kept it. We could remove it without breaking automatic update because all metadata is in a separate file - AFAIK.

**Comment by Jocs** [comment]
>I don't think so because the version was included by default and we kept it. We could remove it without breaking automatic update because all metadata is in a separate file - AFAIK. Or whats the reason to keep it, @Jocs ?

I thought about it, it seems that just to distinguish it from the previous version, removing the version number will bring some convenience to the release. If you feel that it is feasible to remove it, you can remove version number in this time of release.
